### ISSUE TITLE
Install on customer system

### ISSUE THREAD

**Issue by wojosc** [tueit/football_club#1]
Installation breaks. I will look for errors connected to this app.

**Comment by DeeMysterio** [comment]
Is this issue resolved? seemed like an interesting project so I forked and installed it, it installed smoothly.

**Comment by wojosc** [comment]
@DeeMysterio thank you for testing. I will close this issue.

Sorry, we haven't been doing a lot on here lately. We are about to onboard a further football (soccer) club though and will then pick up work once again. Stay tuned!
